---
title: "Yifan"
output: html_document
---
# Code borrowed from wordbank book for setups

```{r}
library(wordbankr)
library(langcog)
library(knitr)
library(feather)
library(tidyverse)

options(DT.options = list(searching = FALSE,
                          lengthChange = FALSE))


opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  echo = FALSE,
  cache.lazy = FALSE,
  fig.align = "center",
  fig.show = "hold",
  dev = "png",
  dpi = 300,
  out.width = "\\linewidth"
)

#.font <- "Source Sans Pro"
.uni_font <- "Gulim"
theme_set(theme_mikabr(base_family = .font))
theme_update(plot.margin = margin(0, 0, 2, 0, "pt"),
             legend.margin = margin(0, 0, 0, 0, "pt"))
.grey <- "grey70"
.refline <- "dotted"
.coef_line <- element_line(colour = .grey, size = 0.1)

.ages <- seq(5, 45, 5)

.pal <- ggthemes::ptol_pal

.scale_colour_discrete <- ggthemes::scale_colour_ptol
.scale_color_discrete <- .scale_colour_discrete
.scale_fill_discrete <- ggthemes::scale_fill_ptol

.scale_colour_continuous <- viridis::scale_colour_viridis
.scale_color_continuous <- .scale_colour_continuous
.scale_fill_continuous <- viridis::scale_fill_viridis

.scale_colour_numerous <- scale_colour_discrete
.scale_color_numerous <- .scale_colour_numerous
.scale_fill_numerous <- scale_fill_discrete

source("helper/predictQR.R")
source("helper/stats_funs.R")

instruments <- read_feather("data/_common/instruments.feather")
admins <- read_feather("data/_common/admins.feather")
items <- read_feather("data/_common/items.feather")


```


# WS

```{r catsyn-items}
items_n <- items %>%
  filter(type == "word",
         form == "WS",
         language == "English (American)") %>%
  mutate(num_item_id = as.numeric(substr(item_id, 6, nchar(item_id))))

items_as <- read_feather("saved_data/all_aoa_WS.feather")%>%
  select(-item) # did not select id

items_as_c <-items_as%>%
  inner_join(items_n, by = c("uni_lemma" = "definition"))%>%
  select(c(6, 12:21))

names(items_as_c)[3]<-"language"
names(items_as_c)[4]<-"form"   
names(items_as_c)[6]<-"category"
```

```{r catsyn-vocab_comp_fun}
get_vocab_data <- function(input_language, input_form) {
  print(paste(input_language, input_form))
  
  lang_vocab_items <- items_as_c %>%
    filter(language == input_language, form == input_form,
           category %in% c("sounds", "body_parts", "games_routines", "vehicles", "animals","toys", "food_drink", "household", "clothing","outside", "furniture_rooms","places", "people", "time_words"))
  
  get_instrument_data(language = input_language,
                      form = input_form,
                      items = lang_vocab_items$item_id, 
                      iteminfo = lang_vocab_items) %>%
    mutate(value = ifelse(is.na(value), "", value),
           produces = value == "produces") %>%
    select(-value) %>%
    gather(measure, value, produces) %>%
    mutate(num_words = nrow(lang_vocab_items),
           language = input_language, form = input_form) %>%
    filter(form %in% WGs | measure == "produces")
}

get_vocab_comp <- function(lang_vocab_data, group) {
  group <- rlang::enquo(group)

  num_words <- n_distinct(lang_vocab_data$item_id)
  lang_vocab_summary <- lang_vocab_data %>%
    group_by(data_id, measure, !!group) %>%
    summarise(num_true = sum(value),
              total = n(),
              prop = num_true / total)

  lang_vocab_sizes <- lang_vocab_summary %>%
    group_by(data_id, measure) %>%
    summarise(vocab_num = sum(num_true),
              vocab = vocab_num / num_words)

  lang_vocab_summary %>%
    left_join(lang_vocab_sizes) %>%
    mutate(prop_vocab = num_true / vocab_num) %>%
    select(-num_true)

}
```

```{r catsyn-vocab_comp, eval=FALSE}
instruments_inc <- instruments %>%
  filter(form == "WS",
         language == "English (American)") %>%
  select(language, form)

vocab_data <- instruments_inc %>%
  mutate(inst_vocab_data = map2(language, form, get_vocab_data))

vocab_comp_category <- vocab_data %>%
  mutate(vocab_comp = map(inst_vocab_data, ~get_vocab_comp(., category)))

vocab_comp_data <- vocab_comp_category %>%
  select(-inst_vocab_data) %>%
  unnest()

```

```{r catsyn-sample-sizes}
form <- "WS"
form_type <- "WSs"

forms <- data_frame(form, form_type)

vocab_comp_data <- vocab_comp_data%>%
  left_join(forms) %>%
  group_by(language, form_type) %>%
  mutate(num_forms = n_distinct(form),
         langform = if_else(num_forms > 1,
                            paste(language, form, sep = .inst_sep), language))
```

```{r}

#feather::write_feather(vocab_comp_data,"saved_data/vocab_comp_data_WS_AS")

vocab_comp_data_AS <- read_feather("saved_data/vocab_comp_data_WS_AS")
vocab_comp_data_TD <- read_feather("saved_data/vocab_comp_data_WS_TD")

pts <- seq(0, 1, 0.01)

# TD
demo_predictions_TD <- vocab_comp_data_TD %>%
  group_by(category) %>%
  nest() %>%
  mutate(model = map(data, ~clm(prop ~ I(vocab ^ 3) + I(vocab ^ 2) + vocab - 1, data = .)),
         predictions = map(model, ~broom::augment(., newdata = tibble(vocab = pts)))) %>%
  select(category, predictions) %>%
  unnest() %>%
  rename(prop = .fitted)%>%
  mutate(level = "TD")

demo_diagonal_TD <- cross_df(list(vocab = rev(pts),
                               category = unique(vocab_comp_data_TD$category))) %>%
  mutate(prop = vocab)

demo_area_poly_TD <- bind_rows(demo_predictions_TD, demo_diagonal_TD)

# AS
demo_predictions_AS <- vocab_comp_data_AS %>%
  group_by(category) %>%
  nest() %>%
  mutate(model = map(data, ~clm(prop ~ I(vocab ^ 3) + I(vocab ^ 2) + vocab - 1, data = .)),
         predictions = map(model, ~broom::augment(., newdata = tibble(vocab = pts)))) %>%
  select(category, predictions) %>%
  unnest() %>%
  rename(prop = .fitted)%>%
  mutate(level = "AS")

demo_diagonal_AS <- cross_df(list(vocab = rev(pts),
                               category = unique(vocab_comp_data_AS$category))) %>%
  mutate(prop = vocab)

demo_area_poly_AS <- bind_rows(demo_predictions_AS, demo_diagonal_AS)

# prediction all

demo_predictions_all <- rbind(demo_predictions_AS,demo_predictions_TD)
demo_predictions_all_c <- cbind(demo_predictions_AS,demo_predictions_TD)

colnames(demo_predictions_all_c)[5:8] <- c("category.y","vocab.y","prop.y","level.y")

demo_predictions_all_c <- demo_predictions_all_c %>%
  mutate(diff = prop - prop.y)
  
vocab_scale <- scale_x_continuous(limits = c(0, 1), expand = c(0.01, 0),
                                  breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1),
                                  name = "Vocabulary size")
prop_scale <- scale_y_continuous(limits = c(0, 1), expand = c(0.01, 0),
                                 breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1),
                                 name = "Proportion of category")

ggplot(demo_predictions_all_c, aes(x = vocab, y = prop, colour = category)) +
  facet_wrap(. ~ category,ncol = 5) +
  coord_fixed() +
  #geom_point(alpha = .03, size = 0.6) +
  geom_line(data = demo_predictions_TD, aes(x = vocab, y = prop), size = .5, color = "grey") +
  geom_line(data = demo_predictions_AS, aes(x = vocab, y = prop), size = .5) +
  geom_polygon(data = demo_area_poly_AS, aes(fill = category), alpha = .1,color = NA) +
  geom_polygon(data = demo_area_poly_TD, aes(fill = category), alpha = .1,color = NA)+
  vocab_scale +
  prop_scale +
  geom_abline(slope = 1, intercept = 0, color = .grey, linetype = .refline)+
  .scale_colour_numerous(guide = FALSE) +
  .scale_fill_numerous(guide = FALSE)+
  theme_bw()+
  labs(title = "WS")
  
```

# WG

```{r catsyn-items}
items_n <- items %>%
  filter(type == "word",
         form == "WG",
         language == "English (American)") %>%
  mutate(num_item_id = as.numeric(substr(item_id, 6, nchar(item_id))))

items_as <- read_feather("all_aoa_WG.feather") %>%
  select(-item)

items_as_c <-items_as%>%
  inner_join(items_n, by = c("uni_lemma" = "definition"))%>%
  select(c(6, 11:20))

names(items_as_c)[3]<-"language"
names(items_as_c)[4]<-"form"   
```

```{r catsyn-vocab_comp_fun}
get_vocab_data <- function(input_language, input_form) {
  print(paste(input_language, input_form))
  
  lang_vocab_items <- items_n %>%
    filter(language == input_language, form == input_form,
           category %in% c("sounds", "body_parts", "games_routines", "vehicles", "animals","toys", "food_drink", "household", "clothing","outside", "furniture_rooms","places", "people", "time_words"))
  
  get_instrument_data(language = input_language,
                      form = input_form,
                      items = lang_vocab_items$item_id, 
                      iteminfo = lang_vocab_items) %>%
    mutate(value = ifelse(is.na(value), "", value),
           understands = value == "understands") %>%
    select(-value) %>%
    gather(measure, value, understands) %>%
    mutate(num_words = nrow(lang_vocab_items),
           language = input_language, form = input_form)
}

get_vocab_comp <- function(lang_vocab_data, group) {
  group <- rlang::enquo(group)

  num_words <- n_distinct(lang_vocab_data$item_id)
  lang_vocab_summary <- lang_vocab_data %>%
    group_by(data_id, measure, !!group) %>%
    summarise(num_true = sum(value),
              total = n(),
              prop = num_true / total)

  lang_vocab_sizes <- lang_vocab_summary %>%
    group_by(data_id, measure) %>%
    summarise(vocab_num = sum(num_true),
              vocab = vocab_num / num_words)

  lang_vocab_summary %>%
    left_join(lang_vocab_sizes) %>%
    mutate(prop_vocab = num_true / vocab_num) %>%
    select(-num_true)

}
```

```{r catsyn-vocab_comp, eval=FALSE}
instruments_inc <- instruments %>%
  filter(form == "WG",
         language == "English (American)") %>%
  select(language, form)

vocab_data <- instruments_inc %>%
  mutate(inst_vocab_data = map2(language, form, get_vocab_data))

vocab_comp_category <- vocab_data %>%
  mutate(vocab_comp = map(inst_vocab_data, ~get_vocab_comp(., category)))

vocab_comp_data <- vocab_comp_category %>%
  select(-inst_vocab_data) %>%
  unnest()

```

```{r catsyn-sample-sizes}
form <- "WG"
form_type <- "WGs"

forms <- data_frame(form, form_type)

vocab_comp_data <- vocab_comp_data%>%
  left_join(forms) %>%
  group_by(language, form_type) %>%
  mutate(num_forms = n_distinct(form),
         langform = if_else(num_forms > 1,
                            paste(language, form, sep = .inst_sep), language))
```

```{r}

#feather::write_feather(vocab_comp_data,"saved_data/vocab_comp_data_WG_TD")

vocab_comp_data_AS <- read_feather("saved_data/vocab_comp_data_WG_AS")
vocab_comp_data_TD <- read_feather("saved_data/vocab_comp_data_WG_TD")

pts <- seq(0, 1, 0.01)

# TD
demo_predictions_TD <- vocab_comp_data_TD %>%
  group_by(category) %>%
  nest() %>%
  mutate(model = map(data, ~clm(prop ~ I(vocab ^ 3) + I(vocab ^ 2) + vocab - 1, data = .)),
         predictions = map(model, ~broom::augment(., newdata = tibble(vocab = pts)))) %>%
  select(category, predictions)%>%
  unnest() %>%
  rename(prop = .fitted)%>%
  mutate(level = "TD")


demo_predictions_TD$prop <- signif(demo_predictions_TD$prop,digits=4 )


demo_diagonal_TD <- cross_df(list(vocab = rev(pts),
                               category = unique(vocab_comp_data_TD$category))) %>%
  mutate(prop = vocab)

demo_area_poly_TD <- bind_rows(demo_predictions_TD, demo_diagonal_TD)

# AS
demo_predictions_AS <- vocab_comp_data_AS %>%
  group_by(category) %>%
  nest() %>%
  mutate(model = map(data, ~clm(prop ~ I(vocab ^ 3) + I(vocab ^ 2) + vocab - 1, data = .)),
         predictions = map(model, ~broom::augment(., newdata = tibble(vocab = pts)))) %>%
  select(category, predictions) %>%
  unnest() %>%
  rename(prop = .fitted)%>%
  mutate(level = "AS")

demo_predictions_AS$prop <- signif(demo_predictions_AS$prop,digits=4 )

demo_diagonal_AS <- cross_df(list(vocab = rev(pts),
                               category = unique(vocab_comp_data_AS$category))) %>%
  mutate(prop = vocab)

demo_area_poly_AS <- bind_rows(demo_predictions_AS, demo_diagonal_AS)

# prediction all

demo_predictions_all <- rbind(demo_predictions_AS,demo_predictions_TD)
demo_predictions_all_c <- cbind(demo_predictions_AS,demo_predictions_TD)

#demo_predictions_all_c$prop.y <- round(demo_predictions_all_c$prop.y, 2)
#demo_predictions_all_c <- round(demo_predictions_all_c$pro, 2)

colnames(demo_predictions_all_c)[5:8] <- c("category.y","vocab.y","prop.y","level.y")

demo_predictions_all_c <- demo_predictions_all_c %>%
  mutate(diff = prop - prop.y)
  
demo_predictions_all_c$prop <- signif(demo_predictions_all_c$prop,digits=2 )

demo_predictions_all_c$prop.y <- signif(demo_predictions_all_c$prop.y,digits=2 )

vocab_scale <- scale_x_continuous(limits = c(0, 1), expand = c(0.01, 0),
                                  breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1),
                                  name = "Vocabulary size")
prop_scale <- scale_y_continuous(limits = c(0, 1.01), expand = c(0.01, 0),
                                 breaks = c(0, 0.5, 1), labels = c(0, 0.5, 1),
                                 name = "Proportion of category")

ggplot(demo_predictions_all_c, aes(x = vocab, y = prop, colour = category)) +
  facet_wrap(. ~ category,ncol = 5) +
  coord_fixed() +
  #geom_point(alpha = .03, size = 0.6) +
  geom_line(data = demo_predictions_TD, aes(x = vocab, y = prop), size = .5, color = "darkgrey") +
  geom_line(data = demo_predictions_AS, aes(x = vocab, y = prop), size = .5) +
  geom_polygon(data = demo_area_poly_AS, aes(fill = category), alpha = .1,color = NA) +
  geom_polygon(data = demo_area_poly_TD, aes(fill = category), alpha = .1,color = NA)+
  vocab_scale +
  prop_scale +
  geom_abline(slope = 1, intercept = 0, color = .grey, linetype = .refline)+
  .scale_colour_numerous(guide = FALSE) +
  .scale_fill_numerous(guide = FALSE)+
  theme_bw()+
  labs(title = "WG")
  
```


```{r}
bp <- demo_predictions_TD %>%
  filter(category == "body_parts") # prop over 1

overlimit_TD <- demo_predictions_TD %>%
  filter(prop >1 )

overlimit_AS <- demo_predictions_AS %>%
  filter(prop >1 )

vocab_comp_data_AS %>%
  filter(prop > 1)

vocab_comp_data_TD %>%
  filter(prop > 1)
```

